name: Test Vuln Action
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
jobs:
  test-vuln-action-from-pr:
    runs-on: ubuntu-latest
    env: # Or as an environment variable
      git_pat: ${{ secrets.GITHUB_TOKEN }}
      super_secret: ${{ secrets.TEST_SECRET }}
    steps:
      - uses: actions/checkout@v4
        with: 
          ref: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Script
        run: |
          bash test.sh
